version: "3.4"
services:
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: pak_local
      POSTGRES_USER: pak_local
      POSTGRES_PASSWORD: aa010203
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
